plugins:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.2
  NewCops: enable

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
    - 'bundler_mcp.gemspec'

RSpec/DescribeClass:
  Exclude:
    - 'spec/integration/**/*'

RSpec/ExampleLength:
  Max: 20

RSpec/MultipleExpectations:
  Exclude:
    - 'spec/integration/**/*'

RSpec/SpecFilePathFormat:
  Enabled: false

Style/FrozenStringLiteralComment:
  Exclude:
    - 'exe/*'

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes
